import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app"

const BaiJamjuree = Bai_Jamjuree({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en" suppressHydrationWarning>
			<body
				// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				className={BaiJamjuree.className}
			>
				<NuqsAdapter>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</NuqsAdapter>
			</body>
		</html>
  )
}
